### ISSUE TITLE
Improve error handling for APIs (e.g query_range)

### ISSUE THREAD

**Issue by bwplotka** [conprof/conprof#77]
Without any params we got weird messages like `failed to parse series labels  with error 1:1: parse error: unexpected end of input`

**Comment by yeya24** [comment]
This will be solved by #88

**Comment by MadhavJivrajani** [comment]
Hi!
Can I take this up?

**Comment by brancz** [comment]
Go for it! :)

Any ideas how?

**Comment by MadhavJivrajani** [comment]
I'm having a little difficulty reproducing the error mentioned, any tips?

**Comment by bwplotka** [comment]
Is there a chance that this was fixed in https://github.com/conprof/conprof/pull/88 ? 

If you cannot repro it's good (: It means it's done. If you confirm we can close. If  you want to contribute still there definitely other issues  as well 🤗

**Comment by brancz** [comment]
Ah very possible yes. Maybe you can re-try with a latest version @bwplotka ?

**Comment by yeya24** [comment]
I can still reproduce this in the current master.

```
curl http://localhost:10902/api/v1/query_range\?from\=1613534702228\&to\=1613534969295
{"status":"error","errorType":"bad_data","error":"1:1: parse error: unexpected end of input"}
```

The problem is that we didn't check whether the parameter `query` is empty or not. Below is the example output for Prometheus.

```
 curl http://localhost:9090/api/v1/query_range\?start\=1613534702228\&end\=1613534969295\&step\=500
{"status":"error","errorType":"bad_data","error":"1:1: parse error: no expression found in input"}
```
